# Generated by Django 6.0.5 on 2026-05-17 05:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gardens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("common_name", models.CharField(max_length=100)),
                ("scientific_name", models.CharField(blank=True, max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vegetable", "Vegetable"),
                            ("herb", "Herb"),
                            ("fruit", "Fruit"),
                            ("flower", "Flower"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["common_name"],
            },
        ),
        migrations.CreateModel(
            name="UserPlant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("variety", models.CharField(blank=True, max_length=100)),
                ("planted_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("planted", "Planted"),
                            ("growing", "Growing"),
                            ("harvested", "Harvested"),
                            ("removed", "Removed"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_plants",
                        to="gardens.gardenbed",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_plants",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
