# Generated by Django 6.0.5 on 2026-05-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_seed_plant_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('vegetable', 'Vegetable'), ('herb', 'Herb'), ('fruit', 'Fruit'), ('flower', 'Flower'), ('other', 'Other')], max_length=20),
        ),
    ]
