# Generated by Django 6.0.5 on 2026-05-20 05:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0002_seed_plant_catalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userplant",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("planted", "Planted"),
                    ("growing", "Growing"),
                    ("dormant", "Dormant"),
                    ("harvested", "Harvested"),
                    ("removed", "Removed"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("observed_date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("status_change", "Status Change"),
                            ("pest", "Pest"),
                            ("weather", "Weather"),
                            ("disease", "Disease"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("previous_status", models.CharField(blank=True, max_length=20)),
                ("new_status", models.CharField(blank=True, max_length=20)),
                (
                    "user_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="plants.userplant",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_date", "-created_at"],
            },
        ),
    ]
