# Generated by Django 6.0.5 on 2026-05-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0003_alter_userplant_status_observation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="observation",
            options={"ordering": ["observed_date", "created_at"]},
        ),
        migrations.AlterField(
            model_name="observation",
            name="type",
            field=models.CharField(
                choices=[
                    ("status_change", "Status Change"),
                    ("harvest", "Harvest"),
                    ("pest", "Pest"),
                    ("weather", "Weather"),
                    ("disease", "Disease"),
                    ("general", "General"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userplant",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("planted", "Planted"),
                    ("growing", "Growing"),
                    ("fruiting", "Fruiting"),
                    ("dormant", "Dormant"),
                    ("removed", "Removed"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
    ]
