# Generated by Django 6.0.5 on 2026-05-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0004_alter_observation_options_alter_observation_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userplant",
            old_name="planted_date",
            new_name="start_date",
        ),
    ]
