# Generated by Django 6.0.5 on 2026-05-20 18:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gardens", "0001_initial"),
        ("plants", "0005_rename_planted_date_to_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "x",
                    models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
                ),
                (
                    "y",
                    models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
                ),
                (
                    "width",
                    models.IntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="gardens.gardenbed",
                    ),
                ),
                (
                    "user_plant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement",
                        to="plants.userplant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
