# Generated by Django 6.0.5 on 2026-05-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0006_plantplacement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="type",
            field=models.CharField(
                choices=[
                    ("status_change", "Status Change"),
                    ("transplant", "Transplant"),
                    ("harvest", "Harvest"),
                    ("pest", "Pest"),
                    ("weather", "Weather"),
                    ("disease", "Disease"),
                    ("general", "General"),
                ],
                max_length=20,
            ),
        ),
    ]
