# Generated by Django 6.0.5 on 2026-05-27 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0007_alter_observation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="default_spacing_ft",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plantplacement",
            name="height",
            field=models.FloatField(
                default=1.0, validators=[django.core.validators.MinValueValidator(0.01)]
            ),
        ),
        migrations.AlterField(
            model_name="plantplacement",
            name="width",
            field=models.FloatField(
                default=1.0, validators=[django.core.validators.MinValueValidator(0.01)]
            ),
        ),
        migrations.AlterField(
            model_name="plantplacement",
            name="x",
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name="plantplacement",
            name="y",
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
