# Generated by Django 6.0.5 on 2026-06-04 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0010_add_missing_plants"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanionPlanting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[("beneficial", "Beneficial"), ("harmful", "Harmful")],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "plant_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companion_a_set",
                        to="plants.plant",
                    ),
                ),
                (
                    "plant_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companion_b_set",
                        to="plants.plant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plant_a", "plant_b"), name="unique_companion_pair"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("plant_a__lt", models.F("plant_b"))),
                        name="companion_plant_a_lt_plant_b",
                    ),
                ],
            },
        ),
    ]
