# Generated by Django 6.0.5 on 2026-06-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0013_backfill_start_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantplacement",
            name="rotation",
            field=models.SmallIntegerField(default=0),
        ),
    ]
