# Generated by Django 6.0.5 on 2026-05-17 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Garden",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gardens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GardenBed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("length", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("depth", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("in", "Inches"),
                            ("ft", "Feet"),
                            ("cm", "Centimeters"),
                            ("m", "Meters"),
                        ],
                        default="ft",
                        max_length=2,
                    ),
                ),
                (
                    "facing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("N", "North"),
                            ("NE", "Northeast"),
                            ("E", "East"),
                            ("SE", "Southeast"),
                            ("S", "South"),
                            ("SW", "Southwest"),
                            ("W", "West"),
                            ("NW", "Northwest"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("avg_sunlight_hours", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("soil_type", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "garden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beds",
                        to="gardens.garden",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
