# Generated by Django 6.0.5 on 2026-05-13 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gardens", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="garden",
            name="location",
        ),
        migrations.AddField(
            model_name="garden",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="garden",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="garden",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="garden",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gardens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
