# Generated by Django 6.0.5 on 2026-05-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gardens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="garden",
            name="length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="garden",
            name="unit",
            field=models.CharField(
                choices=[("in", "Inches"), ("ft", "Feet"), ("cm", "Centimeters"), ("m", "Meters")],
                default="ft",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="garden",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
