# Generated by Django 6.0.5 on 2026-05-16 03:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gardens", "0002_remove_garden_location_garden_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GardenBed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("length", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("depth", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("in", "Inches"),
                            ("ft", "Feet"),
                            ("cm", "Centimeters"),
                            ("m", "Meters"),
                        ],
                        default="ft",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "garden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beds",
                        to="gardens.garden",
                    ),
                ),
            ],
        ),
    ]
