# Generated by Django 6.0.5 on 2026-05-27 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gardens", "0003_bedplacement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bedplacement",
            name="height",
        ),
        migrations.RemoveField(
            model_name="bedplacement",
            name="width",
        ),
        migrations.AlterField(
            model_name="bedplacement",
            name="x",
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name="bedplacement",
            name="y",
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
