# Generated by Django 6.0.5 on 2026-05-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gardens", "0003_gardenbed"),
    ]

    operations = [
        migrations.AddField(
            model_name="gardenbed",
            name="avg_sunlight_hours",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gardenbed",
            name="facing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N", "North"),
                    ("NE", "Northeast"),
                    ("E", "East"),
                    ("SE", "Southeast"),
                    ("S", "South"),
                    ("SW", "Southwest"),
                    ("W", "West"),
                    ("NW", "Northwest"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gardenbed",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gardenbed",
            name="soil_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
