# Generated by Django 6.0.5 on 2026-06-07 03:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gardens", "0007_alter_gardenbed_dimensions_float"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GardenFeaturePlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("shed", "Shed"),
                            ("bench", "Bench"),
                            ("arbor", "Arbor / Arch"),
                            ("trellis", "Trellis"),
                            ("fence", "Fence Section"),
                            ("compost", "Compost Bin"),
                            ("rain_barrel", "Rain Barrel"),
                            ("cold_frame", "Cold Frame"),
                            ("fountain", "Fountain"),
                            ("bird_bath", "Bird Bath"),
                            ("pot", "Pot / Container"),
                            ("tomato_cage", "Tomato Cage"),
                            ("row_cover", "Row Cover / Cloche"),
                            ("custom_rect", "Custom Area (Rectangle)"),
                            ("custom_circle", "Custom Area (Circle)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
                ("x", models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ("y", models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                (
                    "width",
                    models.FloatField(
                        default=1.0, validators=[django.core.validators.MinValueValidator(0.01)]
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        default=1.0, validators=[django.core.validators.MinValueValidator(0.01)]
                    ),
                ),
                (
                    "bed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_placements",
                        to="gardens.gardenbed",
                    ),
                ),
                (
                    "garden",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_placements",
                        to="gardens.garden",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garden_feature_placements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("bed__isnull", True), ("garden__isnull", False)),
                            models.Q(("bed__isnull", False), ("garden__isnull", True)),
                            _connector="OR",
                        ),
                        name="garden_feature_placement_exactly_one_scope",
                    )
                ],
            },
        ),
    ]
