# Generated by Django 6.0.5 on 2026-06-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gardens", "0008_gardenfeatureplacement"),
    ]

    operations = [
        migrations.AddField(
            model_name="bedplacement",
            name="rotation",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="garden",
            name="north_facing",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gardenfeatureplacement",
            name="rotation",
            field=models.SmallIntegerField(default=0),
        ),
    ]
