# Generated by Django 6.0.5 on 2026-06-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gardens", "0009_bedplacement_rotation_garden_north_facing_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="garden",
            old_name="north_facing",
            new_name="orientation",
        ),
    ]
