# Generated by Django 6.0.5 on 2026-06-10 04:21

from django.db import migrations, models

FACING_TO_DEGREES = {
    "N": 0, "NE": 45, "E": 90, "SE": 135,
    "S": 180, "SW": 225, "W": 270, "NW": 315,
}


def facing_to_orientation(apps, schema_editor):
    GardenBed = apps.get_model("gardens", "GardenBed")
    for bed in GardenBed.objects.exclude(facing__isnull=True).exclude(facing=""):
        bed.orientation = FACING_TO_DEGREES.get(bed.facing, 0)
        bed.save(update_fields=["orientation"])


class Migration(migrations.Migration):

    dependencies = [
        ("gardens", "0010_rename_north_facing_garden_orientation"),
    ]

    operations = [
        migrations.AddField(
            model_name="gardenbed",
            name="orientation",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.RunPython(facing_to_orientation, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="gardenbed",
            name="facing",
        ),
    ]
