export const routes = {
  home: () => '/',
  login: () => '/login',
  register: () => '/register',
  forgotPassword: () => '/forgot-password',
  resetPassword: () => '/reset-password',
  gardens: () => '/gardens',
  gardenDetail: (id: string) => `/gardens/${id}`,
  allBeds: () => '/beds',
  bedDetail: (gardenId: string, bedId: string) => `/gardens/${gardenId}/beds/${bedId}`,
  allPlants: () => '/plants',
  plantDetail: (plantId: string) => `/plants/${plantId}`,
  profile: () => '/profile',
  calendar: () => '/calendar',
};
